---
title: "Plots of NY NOAA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(rnoaa)
library(ggplot2)
```

```{r, echo = FALSE}
data("ny_noaa")
weather_df = 
  ny_noaa %>%
  mutate(date = ymd(date)) %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  filter(id == "USW00094728") %>% 
  mutate(name = if_else(id == "USW00094728", "CentralPark_NY", NA_character_)) %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin)
  )
  #filter(year == 2007) 
```
{data-width=650}
-----------------------------------------------------------------------

### Scatterplot of Minimum and Maximum Temperatures at Central Park in 2007
```{r scatterplot, echo=FALSE}

weather_df %>% 
  plot_ly(x = ~tmin, y = ~tmax, type = 'scatter', mode = 'markers', alpha = 0.5) %>% 
  layout(
    title = "Scatterplot of Minimum and Maximum Temperatures at Central Park in 2007", 
   xaxis = list(title = "Minimum Temperature"),
   yaxis = list(title = "Maximum Temperature")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------
### Boxplot of Maximum Temperature in Central Park

```{r Boxplot, echo=FALSE}
box_ggplot = 
  weather_df %>% 
  filter(!is.na(tmax) & is.finite(tmax)) %>%
  mutate(month = as.factor(month)) %>% 
  ggplot(aes(x = month, y = tmax)) + 
  labs(y = "maximum temperature", title = "Boxplot of Maximum Temperature in Central Park") +
  geom_boxplot()

plotly::ggplotly(box_ggplot)
```

### Barplot of Average Monthly Precipitation in Central Park 

```{r barchart, echo=FALSE}
weather_df_bar <- weather_df %>%
  group_by(month) %>%
  summarize(avg_prcp = mean(prcp, na.rm = TRUE)) %>% 
  mutate(
    month = as.factor(month)
  )

bar_ggplot =
  weather_df_bar %>% 
  ggplot(
    aes(x = month, y = avg_prcp)) +
    geom_bar(stat = "identity") +
    labs(x = "Month", y = "Precipitation",title = "Barplot of Average Monthly Precipitation in Central Park")

ggplotly(bar_ggplot)
```
